### ISSUE TITLE
Camera using pic_db_index00, 01, 02 etc.

### ISSUE THREAD

**Issue by Haycam** [RANSoftware/Hikvision-PIC-to-JPG#2]
[datadir0.zip](https://github.com/RANSoftware/Hikvision-PIC-to-JPG/files/15396341/datadir0.zip)

Files as per comments on Youtube.

**Comment by Haycam** [comment]
There are pictures being taken so maybe not the files we require?  Here are all files modified recently minus the PIC file

[datadir0.zip](https://github.com/RANSoftware/Hikvision-PIC-to-JPG/files/15425121/datadir0.zip)

Snapshot of files
![image](https://github.com/RANSoftware/Hikvision-PIC-to-JPG/assets/136435786/2b8e5563-d7a0-47a2-ae98-68dfdb429379)

Snapshot of the downloads page from the camera
![image](https://github.com/RANSoftware/Hikvision-PIC-to-JPG/assets/136435786/4e8e865e-bfb9-44f3-b0a3-be2aa0a41a54)

**Comment by RANSoftware** [comment]
The script now supports cameras using pic_db_index files. Thanks again for providing the files.
